pcl_grid_map_extraction:
  num_processing_threads: 8
  cloud_transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
      r: 0.0
      p: 0.0
      y: 0.0
  cluster_extraction:
    cluster_tolerance: 1
    min_num_points: 1
    max_num_points: 1000000000
    use_max_height_as_cell_elevation: false
    use_cluster: false
  outlier_removal:
    is_remove_outliers: true
    mean_K: 10
    stddev_threshold: 1.0
  downsampling:
    is_downsample_cloud: false
    voxel_size:
      x: 0.1
      y: 0.1
      z: 0.1 
  grid_map:
    min_num_points_per_cell: 1
    max_num_points_per_cell: 1000000000
    resolution: 0.2

    
       
